// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalBlog.Data;

#nullable disable

namespace PersonalBlog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250519162215_AddLearningToProficiencyLevels")]
    partial class AddLearningToProficiencyLevels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PersonalBlog.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentCount = 24,
                            Content = "Content goes here",
                            ImageUrl = "https://via.placeholder.com/600x400",
                            IsFeatured = true,
                            PublishedDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReadMinutes = 12,
                            Slug = "building-scalable-microservices",
                            Summary = "In this comprehensive guide, I share my experience architecting microservices-based systems using .NET Core, including best practices for service communication, data consistency, and deployment strategies.",
                            Title = "Building Scalable Microservices with .NET Core"
                        },
                        new
                        {
                            Id = 2,
                            CommentCount = 18,
                            Content = "Content goes here",
                            ImageUrl = "https://via.placeholder.com/400x250",
                            IsFeatured = false,
                            PublishedDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReadMinutes = 8,
                            Slug = "csharp-10-features",
                            Summary = "Exploring how the latest C# features can help you write more elegant, concise, and maintainable code with practical examples.",
                            Title = "Leveraging C# 10 Features for Cleaner Code"
                        },
                        new
                        {
                            Id = 3,
                            CommentCount = 12,
                            Content = "Content goes here",
                            ImageUrl = "https://via.placeholder.com/400x250",
                            IsFeatured = false,
                            PublishedDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReadMinutes = 10,
                            Slug = "effective-sprint-planning",
                            Summary = "A practical guide to planning and executing effective sprints, based on my experience leading development teams.",
                            Title = "Effective Sprint Planning for Software Teams"
                        },
                        new
                        {
                            Id = 4,
                            CommentCount = 32,
                            Content = "Content goes here",
                            ImageUrl = "https://via.placeholder.com/400x250",
                            IsFeatured = false,
                            PublishedDate = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReadMinutes = 15,
                            Slug = "domain-driven-design",
                            Summary = "How to apply Domain-Driven Design principles to real-world applications with practical C# examples.",
                            Title = "Domain-Driven Design in Practice"
                        },
                        new
                        {
                            Id = 5,
                            CommentCount = 15,
                            Content = "Content goes here",
                            ImageUrl = "https://via.placeholder.com/400x250",
                            IsFeatured = false,
                            PublishedDate = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReadMinutes = 12,
                            Slug = "ci-cd-github-actions",
                            Summary = "A step-by-step tutorial on creating efficient CI/CD pipelines for .NET applications using GitHub Actions.",
                            Title = "Setting Up CI/CD Pipelines with GitHub Actions"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeColor = "primary",
                            Name = "Architecture"
                        },
                        new
                        {
                            Id = 2,
                            BadgeColor = "info",
                            Name = "C# Development"
                        },
                        new
                        {
                            Id = 3,
                            BadgeColor = "success",
                            Name = "Project Management"
                        },
                        new
                        {
                            Id = 4,
                            BadgeColor = "danger",
                            Name = "DevOps"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlogPostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PersonalBlog.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = "Master of Computer Science",
                            Description = "Specialized in Software Engineering and Project Management",
                            EndDate = new DateTime(2015, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "University of Technology",
                            Order = 1,
                            StartDate = new DateTime(2013, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Degree = "Bachelor of Science in Computer Science",
                            Description = "Dean's List, Computer Science Club President",
                            EndDate = new DateTime(2013, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Institution = "State University",
                            Order = 2,
                            StartDate = new DateTime(2009, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PersonalBlog.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Tech Innovations Inc.",
                            Description = "Led development teams of 5-8 members, managing project timelines, resource allocation, and stakeholder communication. Architected and implemented microservices architecture that improved system scalability by 40%.",
                            Order = 1,
                            StartDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "C#, ASP.NET Core, Azure, Microservices, Team Leadership",
                            Title = "Senior Developer & Project Manager"
                        },
                        new
                        {
                            Id = 2,
                            Company = "WebSolutions Co.",
                            Description = "Developed and maintained multiple web applications using .NET Core and React. Implemented CI/CD pipelines that reduced deployment time by 60%.",
                            EndDate = new DateTime(2019, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 2,
                            StartDate = new DateTime(2017, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "C#, JavaScript, React, SQL Server, CI/CD",
                            Title = "Full-Stack Developer"
                        },
                        new
                        {
                            Id = 3,
                            Company = "StartUp Labs",
                            Description = "Worked on front-end development for various client projects. Collaborated closely with UX designers to implement responsive interfaces.",
                            EndDate = new DateTime(2017, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Order = 3,
                            StartDate = new DateTime(2015, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Technologies = "HTML/CSS, JavaScript, Bootstrap",
                            Title = "Junior Software Engineer"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryBadgeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = ".NET",
                            CategoryBadgeColor = "primary",
                            Content = "Content goes here",
                            ImageUrl = "https://via.placeholder.com/600x400",
                            IsFeatured = true,
                            PublishedDate = new DateTime(2024, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "dotnet-8-announcement",
                            Source = "Microsoft",
                            SourceUrl = "https://dotnet.microsoft.com",
                            Summary = "Microsoft has announced .NET 8 with significant performance improvements and new features for developers.",
                            Title = "Announcing .NET 8 - Performance Improvements and New Features"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Security",
                            CategoryBadgeColor = "danger",
                            Content = "Content goes here",
                            ImageUrl = "https://via.placeholder.com/400x250",
                            IsFeatured = false,
                            PublishedDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "javascript-security-update",
                            Source = "Security Weekly",
                            SourceUrl = "#",
                            Summary = "A critical security update has been released for a widely used JavaScript framework. All developers are urged to update immediately.",
                            Title = "Major Security Update for Popular JavaScript Framework"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Architecture",
                            CategoryBadgeColor = "info",
                            Content = "Content goes here",
                            ImageUrl = "https://via.placeholder.com/400x250",
                            IsFeatured = false,
                            PublishedDate = new DateTime(2024, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "microservices-adoption-study",
                            Source = "Tech Insights",
                            SourceUrl = "#",
                            Summary = "A recent industry study reveals that 75% of enterprise organizations have adopted or are planning to adopt microservices architecture.",
                            Title = "New Study Shows Increased Adoption of Microservices Architecture"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DarkModeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DarkModeSecondaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LightModeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LightModeSecondaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitterUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "I specialize in web development and project management with over 8 years of experience building scalable applications and leading development teams.",
                            DarkModeColor = "#00bfff",
                            DarkModeSecondaryColor = "#0099cc",
                            Email = "emad@example.com",
                            GitHubUrl = "https://github.com/emadram",
                            ImageUrl = "https://via.placeholder.com/300",
                            LightModeColor = "#3498db",
                            LightModeSecondaryColor = "#2980b9",
                            LinkedInUrl = "https://linkedin.com/in/emadram",
                            Location = "San Francisco, CA",
                            Name = "Emad Ramezani",
                            Phone = "(123) 456-7890",
                            ResumeUrl = "/files/resume.pdf",
                            Title = "Software Developer & Project Manager",
                            TwitterUrl = "https://twitter.com/emadram"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Models.PodcastEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryBadgeColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodeNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Guests")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PodcastEpisodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AudioUrl = "#",
                            Category = ".NET",
                            CategoryBadgeColor = "primary",
                            DurationMinutes = 45,
                            EpisodeNumber = "E01",
                            Guests = "Jane Smith, Microsoft",
                            ImageUrl = "https://via.placeholder.com/400x400",
                            IsFeatured = true,
                            PublishedDate = new DateTime(2024, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "future-of-dotnet",
                            Summary = "In this episode, we discuss the future of .NET with special guest Jane Smith from Microsoft.",
                            Title = "The Future of .NET Development"
                        },
                        new
                        {
                            Id = 2,
                            AudioUrl = "#",
                            Category = "Career",
                            CategoryBadgeColor = "success",
                            DurationMinutes = 38,
                            EpisodeNumber = "E02",
                            Guests = "John Johnson, Senior Developer at Google",
                            ImageUrl = "https://via.placeholder.com/400x400",
                            IsFeatured = false,
                            PublishedDate = new DateTime(2024, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "career-growth-developers",
                            Summary = "Tips and strategies for growing your career as a software developer.",
                            Title = "Career Growth for Developers"
                        },
                        new
                        {
                            Id = 3,
                            AudioUrl = "#",
                            Category = "Front-End",
                            CategoryBadgeColor = "info",
                            DurationMinutes = 52,
                            EpisodeNumber = "E03",
                            Guests = "Sarah Lee, UI Architect",
                            ImageUrl = "https://via.placeholder.com/400x400",
                            IsFeatured = false,
                            PublishedDate = new DateTime(2024, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "modern-frontend-frameworks",
                            Summary = "Comparing React, Angular, and Vue.js with insights from top front-end developers.",
                            Title = "Modern Front-End Frameworks"
                        });
                });

            modelBuilder.Entity("PersonalBlog.Models.PostCategory", b =>
                {
                    b.Property<int>("BlogPostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlogPostId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PostCategories");

                    b.HasData(
                        new
                        {
                            BlogPostId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            BlogPostId = 2,
                            CategoryId = 2
                        },
                        new
                        {
                            BlogPostId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            BlogPostId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            BlogPostId = 5,
                            CategoryId = 4
                        });
                });

            modelBuilder.Entity("PersonalBlog.Models.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultCategoryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableComments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FaviconUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleAnalyticsId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaKeywords")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PostsPerPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteTagline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitterUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("PersonalBlog.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IconColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Proficiency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Programming Languages",
                            IconClass = "fab fa-microsoft",
                            IconColor = "",
                            Name = "C# / .NET",
                            Proficiency = 95,
                            ProficiencyLevel = 3
                        },
                        new
                        {
                            Id = 2,
                            Category = "Programming Languages",
                            IconClass = "fab fa-js",
                            IconColor = "",
                            Name = "JavaScript / TypeScript",
                            Proficiency = 90,
                            ProficiencyLevel = 3
                        },
                        new
                        {
                            Id = 3,
                            Category = "Programming Languages",
                            IconClass = "fas fa-database",
                            IconColor = "",
                            Name = "SQL",
                            Proficiency = 85,
                            ProficiencyLevel = 3
                        },
                        new
                        {
                            Id = 4,
                            Category = "Programming Languages",
                            IconClass = "fab fa-python",
                            IconColor = "",
                            Name = "Python",
                            Proficiency = 75,
                            ProficiencyLevel = 3
                        },
                        new
                        {
                            Id = 5,
                            Category = "Frameworks & Tools",
                            IconClass = "fab fa-microsoft",
                            IconColor = "",
                            Name = "ASP.NET Core",
                            Proficiency = 90,
                            ProficiencyLevel = 3
                        },
                        new
                        {
                            Id = 6,
                            Category = "Frameworks & Tools",
                            IconClass = "fab fa-react",
                            IconColor = "",
                            Name = "React",
                            Proficiency = 85,
                            ProficiencyLevel = 3
                        },
                        new
                        {
                            Id = 7,
                            Category = "Frameworks & Tools",
                            IconClass = "fab fa-angular",
                            IconColor = "",
                            Name = "Angular",
                            Proficiency = 80,
                            ProficiencyLevel = 3
                        },
                        new
                        {
                            Id = 8,
                            Category = "Frameworks & Tools",
                            IconClass = "fas fa-database",
                            IconColor = "",
                            Name = "SQL Server",
                            Proficiency = 85,
                            ProficiencyLevel = 3
                        },
                        new
                        {
                            Id = 9,
                            Category = "Frameworks & Tools",
                            IconClass = "fab fa-docker",
                            IconColor = "",
                            Name = "Docker",
                            Proficiency = 70,
                            ProficiencyLevel = 3
                        },
                        new
                        {
                            Id = 10,
                            Category = "Frameworks & Tools",
                            IconClass = "fas fa-cloud",
                            IconColor = "",
                            Name = "Azure",
                            Proficiency = 75,
                            ProficiencyLevel = 3
                        },
                        new
                        {
                            Id = 11,
                            Category = "Frameworks & Tools",
                            IconClass = "fab fa-aws",
                            IconColor = "",
                            Name = "AWS",
                            Proficiency = 65,
                            ProficiencyLevel = 3
                        },
                        new
                        {
                            Id = 12,
                            Category = "Frameworks & Tools",
                            IconClass = "fab fa-git-alt",
                            IconColor = "",
                            Name = "Git",
                            Proficiency = 90,
                            ProficiencyLevel = 3
                        },
                        new
                        {
                            Id = 13,
                            Category = "Programming Languages",
                            IconClass = "fas fa-robot",
                            IconColor = "",
                            Name = "Prompt Engineering",
                            Proficiency = 92,
                            ProficiencyLevel = 3
                        });
                });

            modelBuilder.Entity("PersonalBlog.Models.SkillCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SkillCategories");
                });

            modelBuilder.Entity("PersonalBlog.Models.Comment", b =>
                {
                    b.HasOne("PersonalBlog.Models.BlogPost", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("PersonalBlog.Models.PostCategory", b =>
                {
                    b.HasOne("PersonalBlog.Models.BlogPost", "BlogPost")
                        .WithMany("PostCategories")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalBlog.Models.Category", "Category")
                        .WithMany("PostCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PersonalBlog.Models.BlogPost", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostCategories");
                });

            modelBuilder.Entity("PersonalBlog.Models.Category", b =>
                {
                    b.Navigation("PostCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
