# This workflow will build a .NET project
# .github/workflows/dotnet.yml
name: .NET

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore PersonalBlog/PersonalBlog.csproj
    - name: Build
      run: dotnet build PersonalBlog/PersonalBlog.csproj --no-restore
    - name: Test
      run: dotnet test PersonalBlog/PersonalBlog.csproj --no-build --verbosity normal